/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',

    // Or if using `src` directory:
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},

    screens: {
      xllMax: { max: '1599px' },
      xlMax: { max: '1279px' },
      lgMax: { max: '1199px' },
      mdMax: { max: '1024px' },
      smMax: { max: '991px' },
      xsMax: { max: '767px' },
      xxsMax: { max: '575px' },
      ExtraSmall: { max: '400px' },
      MediumExtraSmall: { max: '374px' },
      MediumUltraExtraSmall: { max: '300px' },
      UltraExtraSmall: { max: '261px' },
      xxs: '576px',
      xs: '768px',
      sm: '992px',
      md: '1025px',
      lg: '1200px',
      xl: '1280px',
    },
    colors: {
      website: {
        yellow: '#ECE100',
        navy: '#001A36',
        blue: '#017AC1',
        darkBlue: '#002C5C',
        lightBlue: '#0180C8',
        ultraLightBlue: '#7891AA',
        blackBlue: '#001736',
        onHoverBlue: '#28416E',
        red: '#ED1C23',
        darkRed: '#B51316',
        white: '#FFF',
        lightwhite: '#F8FAFC',
        grey: '#D9D9D9',
        lightGrey: '#FBFBFB',
        black: '#222222',
        lightBlack: '#00142F',
        midBalck: '#233A53',
        bodrerGrey: '#E4E0CF',
        green: '#04AB4B',
        lustRed: '#E71316',
        brightGray: '#EBF0F5',
        prussianBlue: '#002D5A',
        gold: '#F1B200',
        silver: '#ADADAD',
        pictonBlue: '#47B0EA',
        platinum: '#E6E6E6',
        maastrichtBlue: '#001E3F',
        honoluluBlue: '#016FB2',
        coolBlack: '#002C5B',
        bdazzledBlue: '#356399',
        shadowBlue: '#6D8DA4',
        lavenderIndigo: '#9747FF',
        maizeYellow: '#F6C557',
        wildBlueYonder: '#9AAFC8',
        maastrichtDarkBlue: '#00183A',
        antinoBlue: '#013D72',
        azureishWhite: '#DCE6F0',
        eerieBlack: '#1A1A1A',
        aeroBlue: '#75BAE2',
        romansilver: '#808C9D',
        philippineGray: '#8E8E93',
        cyanCornflowerBlue: '#2680C8',
        SilverLakeBlue: '#6D8EB5',
        Cultured: '#F5F5FA',
        DarkGoldenrod: '#BD8D02',
        HeliotropeMagenta: '#B900BD',
        AntiFlashWhite: '#EFF3F8',
        Honeydew: '#E4FFEC',
        LightCoral: '#EC868C',
        Linen: '#FAE8E8',
        SelectiveYellow: '#FBBC05',
        AeroBlue: '#CDEEDB',
        LightRed: '#FBD2D3',
        CookiesAndCream: '#ECDDB3',
        PoliceBlue: '#33485E',
        LightSteelBlue: '#DBC8B6',
        RedishWhite: '#f5eed9',
        LavenderGray: '#BBC8D4 ',
        JetStream: '#C1DDD1',
        DustStorm: '#E4C7CB',
        LightGray: '#DDDDDD',
        DarkSapphire: '#0d3764',
        darkBlack: '#000000',
        lightGreen: '#CBF4DC',
      },
    },
    fontFamily: {
      abolitionRegular: ['Abolition-Regular'],
      abolitionOblique: ['Abolition-Oblique'],
      industryUltra: ['Industry-Ultra'],
      industryBold: ['Industry-Bold'],
      industryDemi: ['Industry-Demi'],
      industryMedium: ['Industry-Medium'],
      EvelethCleanRegular: ['EvelethCleanRegular'],
      EvelethRegular: ['EvelethRegular'],
      EvelethDemo: ['EvelethDemo'],
      EvelethIcons: ['EvelethIcons'],
      MontserratRegular: ['MontserratRegular'],
      MontserratMedium: ['MontserratMedium'],
      MontserratSemiBold: ['MontserratSemiBold'],
      MontserratBold: ['MontserratBold'],
      MontserratThin: ['MontserratThin'],
      Impact: ['Impact'],
    },
    backgroundImage: {
      texture: "url('../public/images/texture.svg')",
    },
  },
}
